name: Generate Snake

on:
  schedule:
    - cron: "* */12 * * *"  # Executa a cada 12 horas
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3  # Atualizando para usar node16

      - name: Generate Snake
        uses: Platane/snk@v2.2.0  # Atualize para a versão mais recente
        with:
          github_user_name: osmarmcn
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Deploy Snake SVG to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3  # Atualize para uma versão que suporte node16
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

